/**
 * Configuration for Enterprise Asset Tables (Books, Manuscripts, Audios, Videos)
 * Matched 1:1 with PostgreSQL Migrations and super_admin_dashboard_preview.html
 */

export const booksColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'title', label: 'العنوان', visible: true, required: true, sortable: true },
    { key: 'slug', label: 'المعرف', visible: true, required: false, sortable: true, isMono: true },
    { key: 'author', label: 'المؤلف', visible: true, required: false, sortable: true },
    { key: 'isbn', label: 'الرقم الدولي', visible: true, required: false, sortable: true, isMono: true },
    { key: 'description', label: 'الوصف', visible: true, required: false },
    { key: 'files', label: 'الملفات', visible: true, required: false, align: 'center' },
    { key: 'created_at', label: 'التاريخ', visible: true, required: false, sortable: true, isMono: true },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const manuscriptsColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'code', label: 'الكود', visible: true, required: true, sortable: true, isMono: true },
    { key: 'title', label: 'العنوان', visible: true, required: true, sortable: true },
    { key: 'original_title', label: 'العنوان الأصلي', visible: false, required: false },
    { key: 'century', label: 'القرن', visible: true, required: false, align: 'center' },
    { key: 'copy_date', label: 'تاريخ النسخ', visible: true, required: false, align: 'center', isMono: true },
    { key: 'copyist', label: 'الناسخ', visible: true, required: false },
    { key: 'parts_count', label: 'الأجزاء', visible: false, required: false, align: 'center' },
    { key: 'dimensions', label: 'الأبعاد', visible: false, required: false, isMono: true },
    { key: 'lines_count', label: 'الأسطر', visible: false, required: false, align: 'center' },
    { key: 'script_type', label: 'الخط', visible: true, required: false },
    { key: 'ink_color', label: 'الحبر', visible: false, required: false },
    { key: 'paper_type', label: 'الورق', visible: false, required: false },
    { key: 'binding_type', label: 'التجليد', visible: false, required: false },
    { key: 'source_library', label: 'المصدر الخزائني', visible: true, required: false },
    { key: 'shelf_number', label: 'رقم الحفظ', visible: true, required: false, isMono: true },
    { key: 'condition', label: 'الحالة', visible: true, required: false, align: 'center' },
    { key: 'incipit', label: 'الفاتحة', visible: false, required: false },
    { key: 'explicit', label: 'الخاتمة', visible: false, required: false },
    { key: 'colophon', label: 'الحرد', visible: false, required: false },
    { key: 'notes', label: 'الملاحظات', visible: false, required: false },
    { key: 'files', label: 'الملفات', visible: true, required: false, align: 'center' },
    { key: 'created_at', label: 'التاريخ', visible: true, required: false, sortable: true, isMono: true },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const audiosColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'title', label: 'العنوان', visible: true, required: true, sortable: true },
    { key: 'code', label: 'الكود', visible: true, required: false, sortable: true, isMono: true },
    { key: 'slug', label: 'المعرف', visible: false, required: false, isMono: true },
    { key: 'duration', label: 'المدة', visible: true, required: false, isMono: true },
    { key: 'format', label: 'الصيغة', visible: true, required: false, align: 'center' },
    { key: 'bitrate', label: 'معدل البت', visible: true, required: false, isMono: true },
    { key: 'sample_rate', label: 'التردد', visible: false, required: false },
    { key: 'file_size', label: 'الحجم', visible: true, required: false, isMono: true },
    { key: 'description', label: 'الوصف', visible: false, required: false },
    { key: 'files', label: 'الملفات', visible: true, required: false, align: 'center' },
    { key: 'created_at', label: 'التاريخ', visible: true, required: false, sortable: true, isMono: true },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const videosColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'title', label: 'العنوان', visible: true, required: true, sortable: true },
    { key: 'code', label: 'الكود', visible: true, required: false, sortable: true, isMono: true },
    { key: 'slug', label: 'المعرف', visible: false, required: false, isMono: true },
    { key: 'duration', label: 'المدة', visible: true, required: false, isMono: true },
    { key: 'format', label: 'الصيغة', visible: true, required: false, align: 'center' },
    { key: 'file_size', label: 'الحجم', visible: true, required: false, isMono: true },
    { key: 'description', label: 'الوصف', visible: false, required: false },
    { key: 'files', label: 'الملفات', visible: true, required: false, align: 'center' },
    { key: 'created_at', label: 'التاريخ', visible: true, required: false, sortable: true, isMono: true },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const sampleBooksRows = [
    {
        id: 1,
        serial: '#10401',
        title: 'فتح الباري شرح صحيح البخاري',
        slug: 'fath-al-bari',
        author: 'ابن حجر العسقلاني',
        isbn: '978-603-500-025-4',
        description: 'أجل شروح صحيح الإمام البخاري وأعظمها نفعاً، تضمن تحرير الروايات وضبط الألفاظ واستنباط الأحكام.',
        files: '🖼️ غلاف + 📄 PDF',
        created_at: 'منذ ساعتين',
    },
    {
        id: 2,
        serial: '#10402',
        title: 'المستصفى من علم الأصول',
        slug: 'al-mustasfa',
        author: 'الإمام الغزالي',
        isbn: '978-9953-34-118-0',
        description: 'من أمهات كتب أصول الفقه الشافعي والمقارن، وتقسيم مدارك الأحكام ومراتب الأدلة.',
        files: '🖼️ غلاف + 📄 PDF',
        created_at: 'أمس',
    },
    {
        id: 3,
        serial: '#10403',
        title: 'مجموع الفتاوى لشيخ الإسلام',
        slug: 'majmu-al-fatawa',
        author: 'ابن تيمية',
        isbn: '978-603-500-025-4',
        description: 'الموسوعة الكبرى في العقيدة والفقه والسلوك، جمع الشيخ ابن قاسم رحمه الله.',
        files: '🖼️ غلاف + 📄 PDF',
        created_at: 'منذ 3 أيام',
    },
    {
        id: 4,
        serial: '#10404',
        title: 'سير أعلام النبلاء',
        slug: 'siyar-alam-al-nubala',
        author: 'الإمام الذهبي',
        isbn: '978-9953-500-02-1',
        description: 'موسوعة تراجم كبرى لأعيان الأمة والعلماء والقراء والمحدثين عبر القرون الهجرية.',
        files: '🖼️ غلاف + 📄 PDF',
        created_at: 'منذ أسبوع',
    },
];

export const sampleManuscriptsRows = [
    {
        id: 1,
        serial: '#20401',
        code: 'MS-KOP-01',
        title: 'صحيح البخاري - المجلد الرابع (نسخة كوبريلي)',
        original_title: 'الجامع المسند الصحيح المختصر',
        century: 'القرن 7 هـ',
        copy_date: '685 هـ',
        copyist: 'علي بن محمد بن وضاح الشهرزوري',
        parts_count: 'المجلد الرابع من 8',
        dimensions: '28 × 20 سم',
        lines_count: '21 سطراً',
        script_type: 'ثلث مشرقي قديم',
        ink_color: 'سواد كربوني، حمرة قانية',
        paper_type: 'كاغد دمشقي مائي',
        binding_type: 'جلد عثماني أصيل بصنجات',
        source_library: 'مكتبة كوبريلي - إسطنبول',
        shelf_number: 'MS-362/4',
        condition: 'ممتازة 95%',
        incipit: 'بسم الله الرحمن الرحيم، باب كيف كان بدء الوحي...',
        explicit: '...وهو حسبي ونعم الوكيل تم السفر بحمد الله.',
        colophon: 'فرغ من نسخه في العشر الأواخر من رجب المبارك.',
        notes: 'عليه قيود سماع وإجازات بخط ابن حجر وابن الجزري.',
        files: '🖼️ 420 لوحة (TIFF)',
        created_at: 'منذ 3 ساعات',
    },
];

export const sampleAudiosRows = [
    {
        id: 1,
        serial: '#30101',
        title: 'شرح كتاب التوحيد - المجلس الأول',
        code: 'AUD-ABD-01',
        slug: 'sharh-kitab-tawhid-01',
        duration: '01:24:15',
        format: 'MP3 High Quality',
        bitrate: '320 kbps',
        sample_rate: '44.1 kHz',
        file_size: '115 MB',
        description: 'المجلس الافتتاحي لشرح كتاب التوحيد لشيخ الإسلام محمد بن عبد الوهاب، قراءة وتحقيق متون.',
        files: '🎧 صوتي + 🖼️ غلاف',
        created_at: 'أمس',
    },
];

export const sampleVideosRows = [
    {
        id: 1,
        serial: '#40101',
        title: 'ندوة فهارس المخطوطات والرقمنة السحابية',
        code: 'VID-NDW-01',
        slug: 'manuscripts-cataloging-seminar',
        duration: '02:15:00',
        format: 'MP4 4K UltraHD',
        file_size: '3.4 GB',
        description: 'ندوة علمية تفاعلية حول رقمنة المخطوطات الإسلامية وحفظ الفهارس في البيئات السحابية الحديثة.',
        files: '▶️ مرئي + 🖼️ غلاف',
        created_at: 'منذ يومين',
    },
];

export const authorsColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'name', label: 'الاسم / العلم', visible: true, required: true, sortable: true },
    { key: 'slug', label: 'المعرف', visible: false, required: false, sortable: true, isMono: true },
    { key: 'century_lived', label: 'القرن', visible: true, required: false, align: 'center', sortable: true },
    { key: 'lifespan', label: 'العصر والوفاة', visible: true, required: false, align: 'center', isMono: true },
    { key: 'original_region', label: 'الموطن / البلد', visible: true, required: false, sortable: true },
    { key: 'madhab', label: 'المذهب الفقهي', visible: true, required: false, sortable: true },
    { key: 'works_count', label: 'المصنفات بالأرشيف', visible: true, required: false, align: 'center', sortable: true },
    { key: 'bio', label: 'نبذة السيرة', visible: true, required: false },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const sampleAuthorsRows = [
    {
        id: 1,
        serial: '#34001',
        name: 'ابن حجر العسقلاني',
        slug: 'ibn-hajar-al-asqalani',
        century_lived: 'القرن 9 هـ',
        lifespan: '773 - 852 هـ',
        original_region: 'القاهرة / مصر',
        madhab: 'شافعي',
        works_count: '48 مصنفاً',
        bio: 'أحمد بن علي بن حجر العسقلاني، الإمام الحافظ المحدث، أمير المؤمنين في الحديث، صاحب فتح الباري والإصابة وبلوغ المرام.',
    },
    {
        id: 2,
        serial: '#34002',
        name: 'الإمام البخاري',
        slug: 'al-bukhari',
        century_lived: 'القرن 3 هـ',
        lifespan: '194 - 256 هـ',
        original_region: 'بخارى / أوزبكستان',
        madhab: 'محدث / مجتهد',
        works_count: '12 مصنفاً ومخطوطاً',
        bio: 'محمد بن إسماعيل بن إبراهيم البخاري، إمام الحديث والعلل، صاحب الجامع الصحيح والتاريخ الكبير.',
    },
    {
        id: 3,
        serial: '#34003',
        name: 'شمس الدين الذهبي',
        slug: 'al-dhahabi',
        century_lived: 'القرن 8 هـ',
        lifespan: '673 - 748 هـ',
        original_region: 'دمشق / الشام',
        madhab: 'شافعي',
        works_count: '35 مصنفاً',
        bio: 'محمد بن أحمد بن عثمان الذهبي، إمام التاريخ والتراجم، صاحب سير أعلام النبلاء وتاريخ الإسلام وميزان الاعتدال.',
    },
    {
        id: 4,
        serial: '#34004',
        name: 'الإمام النووي',
        slug: 'al-nawawi',
        century_lived: 'القرن 7 هـ',
        lifespan: '631 - 676 هـ',
        original_region: 'نوى / الشام',
        madhab: 'شافعي',
        works_count: '24 مصنفاً',
        bio: 'يحيى بن شرف النووي، شيخ المذهب ومحيي السنة، صاحب المنهاج ورياض الصالحين وشرح صحيح مسلم والأذكار.',
    },
    {
        id: 5,
        serial: '#34005',
        name: 'شيخ الإسلام ابن تيمية',
        slug: 'ibn-taymiyyah',
        century_lived: 'القرن 8 هـ',
        lifespan: '661 - 728 هـ',
        original_region: 'حران / دمشق',
        madhab: 'حنبلي',
        works_count: '62 مصنفاً',
        bio: 'أحمد بن عبد الحليم بن عبد السلام الحراني الدمشقي، الإمام المجدد والفقيه المجتهد، صاحب مجموع الفتاوى ودرء التعارض.',
    },
];

export const publishersColumns = [
    { key: 'serial', label: 'الرقم', visible: true, required: false, sortable: true, isMono: true },
    { key: 'name', label: 'دار النشر / المؤسسة', visible: true, required: true, sortable: true },
    { key: 'slug', label: 'المعرف', visible: false, required: false, sortable: true, isMono: true },
    { key: 'country', label: 'المقر والبلد', visible: true, required: false, align: 'center', sortable: true },
    { key: 'established_year', label: 'سنة التأسيس', visible: true, required: false, align: 'center', sortable: true, isMono: true },
    { key: 'publications_count', label: 'المطبوعات المؤرشفة', visible: true, required: false, align: 'center', sortable: true },
    { key: 'status', label: 'حالة الاعتماد', visible: true, required: false, align: 'center' },
    { key: 'created_at', label: 'تاريخ الإضافة', visible: true, required: false, align: 'center', isMono: true },
    { key: 'actions', label: 'الإجراءات', visible: true, required: true, align: 'center' },
];

export const samplePublishersRows = [
    {
        id: 1,
        serial: '#50001',
        name: 'دار الرسالة العالمية',
        slug: 'dar-al-risalah',
        country: 'بيروت - لبنان',
        established_year: '1970',
        publications_count: '412 مطبوعة',
        status: 'ناشر معتمد 🏢',
        created_at: 'منذ شهر',
    },
    {
        id: 2,
        serial: '#50002',
        name: 'دار المنهاج للنشر والتوزيع',
        slug: 'dar-al-minhaj',
        country: 'جدة - السعودية',
        established_year: '1998',
        publications_count: '285 مطبوعة',
        status: 'ناشر معتمد 🏢',
        created_at: 'منذ شهرين',
    },
    {
        id: 3,
        serial: '#50003',
        name: 'دار ابن حزم للطباعة والنشر',
        slug: 'dar-ibn-hazm',
        country: 'بيروت - لبنان',
        established_year: '1988',
        publications_count: '340 مطبوعة',
        status: 'ناشر معتمد 🏢',
        created_at: 'منذ 3 أشهر',
    },
    {
        id: 4,
        serial: '#50004',
        name: 'مركز المخطوطات والوثائق الإسلامية',
        slug: 'islamic-manuscripts-center',
        country: 'القاهرة - مصر',
        established_year: '2005',
        publications_count: '95 إصداراً',
        status: 'شريك أكاديمي 🏛️',
        created_at: 'منذ 6 أشهر',
    },
];
